spring:
  application:
    name: erni-demo-rag
server:
  forward-headers-strategy: ${FORWARD_HEADERS_STRATEGY:framework}
  
springdoc:
  swagger-ui.path: /swagger
  api-docs.path: /api-docs
  packages-to-scan: ch.erni.edd.demo.rag
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

erni:
  resources.dir: ./src/main/resources #can be overridden in application.properties
  llm:
    openai:
      api-key: <edit in application.properties>
  vector_store:
    pinecone:
      api_key: <edit in application.properties>
      index: edd-demo-rag
      namespace: <edit in application.properties, use your username>

langchain4j:
  open-ai:
    embedding-model:
      api-key: ${erni.llm.openai.api-key}
      model-name: text-embedding-ada-002
    chat-model:
      api-key: ${erni.llm.openai.api-key}
      model-name: gpt-4o-mini
      log-requests: true
      log-responses: true

  
logging:
  level:
    dev.langchain4j: DEBUG
    dev.ai4j.openai4j: DEBUG